# Generated by Django 5.0.2 on 2024-06-03 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('logged_in_datetime', models.DateTimeField(auto_now_add=True)),
                ('logged_out_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('source', models.CharField(max_length=30)),
                ('auth_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('fcm_id', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_session_log',
            },
        ),
    ]
